apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hm-shop
type: Opaque
data:
  POSTGRES_USER:     aG11c2Vy
  POSTGRES_PASSWORD: SE1TaG9wQERCMjAyNA==
  POSTGRES_DB:       aG1zaG9w
